# LWhitelist - https://github.com/karpen-dev/

# Debug
debug: true

# Api settings
api:

  # Url ban
  ban:
    url: "https://example.com/api/v1/ban?name=" # + username + api + reason

  # Url unban
  unban:
    url: "https://example.com/api/v1/unban?name=" # + username + api

  key: "API_KEY"

# Database url
db-url: "jdbc:mysql://localhost:3306/list"

# Database user
db-user: "root"

# Database password
db-password: "root"