name: LWhitelist
version: '1.4'
main: com.karpen.lWhitelist.LWhitelist
api-version: '1.21'

commands:
  vlist:
    usage: /vlist <add | ban>
    permission: karpen.lwlist.vlist

  vlist-reload:
    usage: /vlist-reload
    permission: karpen.lwlist.reload